export default [
  {
    id: 1,
    name: "Alicia River",
    location: "Lahore",
    email: "alicia.rivera@example.com",
    phone: "(459) 239-2229",
    isContact: false,
  },
  {
    id: 2,
    name: "Sylvia Rice",
    location: "Islamabad",
    email: "sylvia.rice@example.com",
    phone: "(977) 915-0667",
    isContact: true,
  },
  {
    id: 3,
    name: "Sylvia Rice",
    location: "Islamabad",
    email: "sylvia.rice@example.com",
    phone: "(977) 915-0667",
    isContact: true,
  },
  {
    id: 4,
    name: "Sylvia Rice",
    location: "Islamabad",
    email: "sylvia.rice@example.com",
    phone: "(977) 915-0667",
    isContact: true,
  },
  {
    id: 5,
    name: "Sylvia Rice",
    location: "Islamabad",
    email: "sylvia.rice@example.com",
    phone: "(977) 915-0667",
    isContact: true,
  },
  {
    id: 6,
    name: "Sylvia Rice",
    location: "Islamabad",
    email: "sylvia.rice@example.com",
    phone: "(977) 915-0667",
    isContact: true,
  },
];
