export default [
  {
    key: 1,
    name: "Mushkpuri Top",
    description: "From Lahore: Day Trip to Champagne with 8 places & Lunch",
    rating: 4.2,
    price: 180,
    tag: "mountain",
    tripType: "Day Trip",
  },
  {
    key: 2,
    name: "Naran Kaghan",
    description: "From Lahore: Day Trip to Champagne with 8 places & Lunch",
    rating: 4.4,
    price: 180,
    tag: "mountain",
    tripType: "3 Day Trip",
  },
  {
    key: 3,
    name: "Naran Kaghan",
    description: "From Lahore: Day Trip to Champagne with 8 places & Lunch",
    rating: 4.4,
    price: 70,
    tag: "mountain",
    tripType: "3 Day Trip",
  },
  {
    key: 4,
    name: "Naran Kaghan",
    description: "From Lahore: Day Trip to Champagne with 8 places & Lunch",
    rating: 4.4,
    price: 180,
    tag: "mountain",
    tripType: "3 Day Trip",
  },
  {
    key: 5,
    name: "Naran Kaghan",
    description: "From Lahore: Day Trip to Champagne with 8 places & Lunch",
    rating: 4.4,
    price: 50,
    tag: "mountain",
    tripType: "3 Day Trip",
  },
];
